application = {
    applicationName: tstr,
    nodes: [ * node ],
}

node = {
    task: tstr,
    name: tstr,
    type: "producer" / "prosumer" / "consumer",
    description: tstr,
    executor: "container",
    container: {
        image: tstr,
        resources: {
            cpu: uint,
            memory: uint,
            taskComplexity: uint,
        }
    },
    communicationTask: {
        ? payloadSize: uint,
    },
    ? downstream: [ * tstr ],
}
