{
  "applicationName": "WordCount"
  "nodes": [
    {
      "task": "1",
      "name": "text2lines",
      "type": "source",
      "description": "Splits text into lines.",
      "executor": "container",
      "container": {
        "image": "text2lines-image",
        "resources": {
          "cpu": "1",
          "memory": "1GB"
          "task-complexity":"no_of_instructions" 
        }
      },
      "comm-task":{
        "payload": ""
      },
      "outputs": ["2", "3"]
    },
    {
      "task": "2",
      "name": "lines2words1",
      "type": "prosumer",
      "description": "Splits lines into words (stream 1).",
      "executor": "container",
      "container": {
        "image": "lines2words-image",
        "resources": {
          "cpu": "1",
          "memory": "1GB"
          "task-complexity":"no_of_instructions" 
        }
      },
      "comm-task":{
        "payload": ""
      },
      "dependencies": ["1"],
      "outputs": ["4"]
    },
    {
      "task": "3",
      "name": "lines2words2",
      "type": "prosumer",
      "description": "Splits lines into words (stream 2).",
      "executor": "container",
      "container": {
        "image": "lines2words-image",
        "resources": {
          "cpu": "1",
          "memory": "1GB",
          "task-complexity":"no_of_instructions" 
        }
      },
      "comm-task":{
        "payload": ""
      },
      "dependencies": ["1"],
      "outputs": ["4"]
    },
    {
      "task": "4",
      "name": "wordcount",
      "type": "sink",
      "description": "Counts the frequency of words.",
      "executor": "container",
      "container": {
        "image": "wordcount-image",
        "resources": {
          "cpu": "2",
          "memory": "2GB",
          "task-complexity":"no_of_instructions"
        }
      },
      "comm-task":{
        "payload": ""
      },
      "dependencies": ["2", "3"]
    }
  ]
}
