Consumer:
  subSyncPrefix: /VP/imageSource
  subPrefixDataMain: /imageSource/dataMain
  subPrefixDataManifest: /imageSource/dataManifest/0
  subPrefixAck: /imageSource/ack
  nSub: [0, 1, 2]
  inputThreshold: 100

Producer:
  pubSyncPrefix: /VP/personDetection/0
  userPrefixDataMain: /personDetection/0/dataMain
  userPrefixDataManifest: /personDetection/0/dataManifest
  userPrefixAck: /personDetection/0/ack
  nDataStreams: 1
  publishInterval: 0
  publishIntervalNew: 100
  outputThreshold: 100
  namesInManifest: 200
  mapThreshold: 100
  computeThreads: 1
Measurement:
  nodeName: PeopleCounter
  saveInterval: 100
