Consumer:
  sub_syncPrefix            : /SampleJson
  sub_Prefix_data_main      : /functionA/dataMain
  sub_Prefix_data_manifest  : /functionA/dataManifest/0
  sub_Prefix_ack            : /functionA/ack
  nSub                      : [1,2,3]
  input_threshold           : 200

Producer:
  pub_syncPrefix             : /SampleJson/functionB
  userPrefix_data_main       : /functionB/dataMain
  userPrefix_data_manifest   : /functionB/dataManifest
  userPrefix_ack             : /functionB/ack
  nDataStreams               : 1
  publish_interval           : 0
  publish_interval_new       : 100
  output_threshold           : 50
  names_in_manifest          : 200
  map_threshold              : 200
