Consumer1:
  subSyncPrefix: /VP/emotion
  subPrefixDataMain: /emotion/dataMain
  subPrefixDataManifest: /emotion/dataManifest/0
  subPrefixAck: /emotion/ack
  nSub: [0]
  inputThreshold: 1

Consumer2:
  subSyncPrefix: /VP/age
  subPrefixDataMain: /age/dataMain
  subPrefixDataManifest: /age/dataManifest/0
  subPrefixAck: /age/ack
  nSub: [0]
  inputThreshold: 1

Consumer3:
  subSyncPrefix: /VP/gender
  subPrefixDataMain: /gender/dataMain
  subPrefixDataManifest: /gender/dataManifest/0
  subPrefixAck: /gender/ack
  nSub: [0]
  inputThreshold: 1

Consumer4:
  subSyncPrefix: /VP/personDetection/0
  subPrefixDataMain: /personDetection/0/dataMain
  subPrefixDataManifest: /personDetection/0/dataManifest/0
  subPrefixAck: /personDetection/0/ack
  nSub: [0]
  inputThreshold: 1

Consumer_5:
  subSyncPrefix: /VP/personDetection/1
  subPrefixDataMain: /personDetection/1/dataMain
  subPrefixDataManifest: /personDetection/1/dataManifest/0
  subPrefixAck: /personDetection/1/ack
  nSub: [0]
  inputThreshold: 1

Consumer_6:
  subSyncPrefix: /VP/personDetection/2
  subPrefixDataMain: /personDetection/2/dataMain
  subPrefixDataManifest: /personDetection/2/dataManifest/0
  subPrefixAck: /personDetection/2/ack
  nSub: [0]
  inputThreshold: 1

Measurement:
  nodeName: Aggregate
  saveInterval: 100
