name: Build Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run : |
          echo "deb [arch=amd64 trusted=yes] https://nfd-nightly-apt.ndn.today/ubuntu jammy main" \
          | sudo tee /etc/apt/sources.list.d/nfd-nightly.list
          sudo apt update
          sudo apt install libndn-cxx-dev libpsync-dev libyaml-cpp-dev libopencv-dev nlohmann-json3-dev cppcheck doxygen

      - name: Generate CMake Build Files
        run: cmake -DBUILD_TESTS=ON .

      - name: Verify Formatting
        run: make check-format

      - name: Lint Codebase
        run: make lint

      - name: Build IceFlow Example Applications and Tests
        run: make

      - name: Run Tests
        run: make test

      - name: Export IceFlow Example Application Binaries
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-binaries
          path: |
            build/agedetection
            build/aggregate
            build/facedetection
            build/genderdetection
            build/imagesource
            build/peoplecounter

  build-macos:
    runs-on: macos-latest
    needs: build-ubuntu

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: brew install boost openssl pkg-config opencv nlohmann-json yaml-cpp clang-format cppcheck

      - name: Install ndn-cxx
        run: |
          git clone https://github.com/named-data/ndn-cxx
          cd ndn-cxx
          ./waf configure
          ./waf
          sudo ./waf install
          cd ..

      - name: Install PSync
        run: |
          git clone https://github.com/named-data/PSync.git
          cd PSync
          ./waf configure
          ./waf
          sudo ./waf install
          cd ..

      - name: Generate CMake Build Files
        run: cmake -DBUILD_TESTS=ON .

      - name: Verify Formatting
        run: make check-format

      - name: Lint Codebase
        run: make lint

      - name: Build IceFlow Example Applications and Tests
        run: make

      - name: Run Tests
        run: make test

      - name: Export IceFlow Example Application Binaries
        uses: actions/upload-artifact@v3
        with:
          name: macos-binaries
          path: |
            build/agedetection
            build/aggregate
            build/facedetection
            build/genderdetection
            build/imagesource
            build/peoplecounter
