name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:
    branches: [ main ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Generate CMake Build Files
        run: nix develop --impure .#ci -c cmake -DBUILD_TESTS=ON .

      - name: Verify Formatting
        run: nix develop --impure .#ci -c make check-format

      - name: Lint Codebase
        run: nix develop --impure .#ci -c make lint

      - name: Build IceFlow Example Applications and Tests
        run: nix develop --impure .#ci -c make

      - name: Run Tests
        run: nix develop --impure .#ci -c make test

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Generate CMake Build Files
        run: nix develop --impure .#ci -c cmake -DBUILD_TESTS=ON .

      - name: Verify Formatting
        run: nix develop --impure .#ci -c make check-format

      - name: Lint Codebase
        run: nix develop --impure .#ci -c make lint

      - name: Build IceFlow Example Applications and Tests
        run: nix develop --impure .#ci -c make

      - name: Run Tests
        run: nix develop --impure .#ci -c make test
