name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Generate CMake Build Files
        run: nix develop --impure .#ci -c cmake -DBUILD_TESTS=ON .
      - name: Build Documentation
        run: nix develop --impure .#ci -c make docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs/html'

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
